--Author: Ana H. Esnard
--Date: 09/24/2019
--Definition :
--  OCUSMA migration

--Modified
--     Date        By                Modification Description
--     11/20/19    LERINA            ADDED JOIN TO OOHEAD TO FILTER OUT CUSTOMERS THAT HAVEN'T ORDERED IN 18 MONTHS

--GRANT SELECT ON MIGRATION.MGVOCUSMA TO M3DBREADS
--CREATE OR REPLACE VIEW MIGRATION.MGVOCUSMA AS

SELECT A.* FROM M3FDBPRD.OCUSMA AS A
INNER JOIN M3FDBPRD.OOHEAD ON OKCUNO=OACUNO
WHERE OKCONO = 100 AND
      OKSTAT = '20' AND
      OARGDT >= TO_CHAR(DATE(NOW() - 1.5 YEAR), 'YYYYMMDD')
      
GROUP BY OKCONO,OKDIVI,OKSTAT,OKCUNO,OKCUCL,OKCUTP,OKALCU,OKCUNM,OKCUA1,OKCUA2,OKCUA3,
OKCUA4,OKADID,OKADBO,OKPHNO,OKPHN2,OKTFNO,OKCORG,OKCOR2,OKYREF,OKYRE2,OKOREF,OKCUSU,
OKEXCD,OKTEPY,OKOT75,OKTECD,OKTEDL,OKMODL,OKSMCD,OKRESP,OKRONO,OKDIPC,OKDISY,OKDIGC,
OKVTCD,OKTXAP,OKCUCD,OKCRTP,OKPLTB,OKPRVG,OKBREC,OKDTFM,OKEDIT,OKORTP,OKWHLO,OKPRIC,
OKSDST,OKCSCD,OKAGNT,OKAGN2,OKAGN3,OKAGN4,OKAGN5,OKAGN6,OKAGN7,OKINSU,OKPYNO,OKCUST,
OKTEPA,OKLHCD,OKCRLM,OKCRL2,OKCRL3,OKBLCD,OKPRIO,OKTBLG,OKTOIN,OKTDIN,OKLIDT,OKININ,
OKACRF,OKAICD,OKBOCD,OKFRE1,OKFRE2,OKBGRP,OKDOGR,OKBLII,OKIICT,OKCLCD,OKBLPR,OKRMCT,
OKBLAC,OKADCA,OKPYDI,OKPONO,OKAUGI,OKAGPA,OKCCUS,OKWAYB,OKADTG,OKODTG,OKMAIL,OKENHD,
OKEURI,OKEDIP,OKCFC1,OKCFC2,OKCFC3,OKCFC4,OKCFC5,OKCFC6,OKCFC7,OKCFC8,OKCFC9,OKCFC0,
OKLSID,OKLSAD,OKMEAL,OKVRNO,OKAGCH,OKAGCT,OKDUCD,OKUSR1,OKUSR2,OKUSR3,OKDTE1,OKDTE2,
OKDTE3,OKCDRC,OKINCO,OKINSN,OKCUIC,OKINSS,OKNALI,OKDTL1,OKUSL1,OKINLI,OKDTL2,OKUSL2,
OKVRCD,OKEDES,OKROUT,OKRODN,OKULZO,OKECLC,OKECF1,OKECF2,OKECF3,OKECF4,OKECF5,OKPYCD,
OKGRPY,OKTXID,OKSERC,OKSRES,OKTECH,OKTRTI,OKLZON,OKDIST,OKTVCD,OKSOTP,OKMTIC,OKPWMT,
OKBPCD,OKBPEX,OKACHK,OKTINC,OKBUSE,OKTCEX,OKPYOP,OKALWT,OKPOPN,OKSOOP,OKPRS1,OKPRS2,
OKPRS3,OKPRS4,OKPRS5,OKDMSO,OKLSOI,OKODUD,OKODUE,OKEALO,OKECAR,OKGEOC,OKTECN,OKTEEC,
OKAGPY,OKAGCP,OKAGAC,OKAGBP,OKACLB,OKAACB,OKAGPN,OKAGBG,OKAGPG,OKAGCA,OKAGTD,OKAGTN,
OKINRC,OKCESA,OKCHSY,OKTAXC,OKHAFE,OKOT89,OKPRDL,OKMCON,OKRAN1,OKRAN2,OKRAN3,OKRAN4,
OKQUCK,OKIVGP,OKACEI,OKVDLA,OKFACI,OKDTID,OKDESV,OKCHCL,OKMCOS,OKSPLM,OKEXPT,OKATPR,
OKACGR,OKSTMS,OKSTMR,OKBCKO,OKPADL,OKTOWN,OKADVI,OKESAL,OKRGDT,OKRGTM,OKLMDT,OKCHNO,
OKCHID,OKLMTS,OKSCED,OKOT86,OKBOP1,OKRPLT,OKRDIS,OKRPYN,OKRTEP,OKRSMC,OKTRSU,OKAOTP,
OKCUEX,OKFRCO,OKSPLE,OKRASN
